package main

import "strings"

// Kind labels shown as filter tabs on the catalog page. A provider absent
// from providerKind falls under KindUnclassified rather than being guessed.
const (
	KindATS          = "ATS platform"
	KindAggregator   = "Aggregator"
	KindCareerSite   = "Career site"
	KindUnclassified = "Unclassified"
)

// providerKind classifies every provider board-console currently knows
// about, by hand. Edit this map directly to reclassify a provider or add a
// newly-onboarded one — a provider missing from it shows under the
// Unclassified tab rather than being guessed.
var providerKind = map[string]string{
	"adp":                 KindATS,
	"applicantpro":        KindATS,
	"applitrack":          KindATS,
	"arbeitsagentur":      KindATS,
	"ashby":               KindATS,
	"ashbygraphql":        KindATS,
	"avature":             KindATS,
	"bamboohr":            KindATS,
	"betterteam":          KindATS,
	"breezy":              KindATS,
	"briefhq":             KindATS,
	"bullhorn":            KindATS,
	"careerplug":          KindATS,
	"catsone":             KindATS,
	"cleverstaff":         KindATS,
	"clinch":              KindATS,
	"comeet":              KindATS,
	"compleo":             KindATS,
	"cornerstone":         KindATS,
	"crelate":             KindATS,
	"dayforce":            KindATS,
	"deel":                KindATS,
	"earcu":               KindATS,
	"edjoin":              KindATS,
	"eightfold":           KindATS,
	"enlizt":              KindATS,
	"epam":                KindATS,
	"erecruiter":          KindATS,
	"factorial":           KindATS,
	"freshteam":           KindATS,
	"gem":                 KindATS,
	"greenhouse":          KindATS,
	"gupy":                KindATS,
	"gusto":               KindATS,
	"herp":                KindATS,
	"hibob":               KindATS,
	"hireology":           KindATS,
	"hiringthing":         KindATS,
	"hrmdirect":           KindATS,
	"hrmos":               KindATS,
	"huntflow":            KindATS,
	"hurma":               KindATS,
	"icims":               KindATS,
	"inhire":              KindATS,
	"ismartrecruit":       KindATS,
	"isolvedhire":         KindATS,
	"jazzhr":              KindATS,
	"jibe":                KindATS,
	"jobscore":            KindATS,
	"jobvite":             KindATS,
	"join":                KindATS,
	"keka":                KindATS,
	"lever":               KindATS,
	"likeit":              KindATS,
	"loxo":                KindATS,
	"luxoft":              KindATS,
	"manatal":             KindATS,
	"mindsight":           KindATS,
	"neogov":              KindATS,
	"northstone":          KindATS,
	"odoo":                KindATS,
	"opencats":            KindATS,
	"oracle":              KindATS,
	"pageup":              KindATS,
	"paycom":              KindATS,
	"paycor":              KindATS,
	"paylocity":           KindATS,
	"peopleforce":         KindATS,
	"personio":            KindATS,
	"phenom":              KindATS,
	"pinpoint":            KindATS,
	"quickin":             KindATS,
	"radancy":             KindATS,
	"rapyd":               KindATS,
	"recruitee":           KindATS,
	"recruitingsolutions": KindATS,
	"rippling":            KindATS,
	"senior":              KindATS,
	"smartrecruiters":     KindATS,
	"softgarden":          KindATS,
	"solides":             KindATS,
	"spark":               KindATS,
	"speedrun":            KindATS,
	"successfactors":      KindATS,
	"talentadore":         KindATS,
	"talenthr":            KindATS,
	"talentlyft":          KindATS,
	"taleo":               KindATS,
	"teamtailor":          KindATS,
	"traffit":             KindATS,
	"trakstar":            KindATS,
	"trudvsem":            KindATS,
	"ukg":                 KindATS,
	"ukgready":            KindATS,
	"vention":             KindATS,
	"vouch":               KindATS,
	"workable":            KindATS,
	"workablemarketplace": KindATS,
	"workday":             KindATS,
	"workstream":          KindATS,
	"wpyoast":             KindATS,
	"zohorecruit":         KindATS,
	"4dayweek":            KindAggregator,
	"adzuna":              KindAggregator,
	"aijobs":              KindAggregator,
	"arbeitnow":           KindAggregator,
	"bayt":                KindAggregator,
	"cryptocurrencyjobs":  KindAggregator,
	"djinni":              KindAggregator,
	"echojobs":            KindAggregator,
	"functionalworks":     KindAggregator,
	"geekjob":             KindAggregator,
	"getmanfred":          KindAggregator,
	"getmatch":            KindAggregator,
	"getonbrd":            KindAggregator,
	"getro":               KindAggregator,
	"gulftalent":          KindAggregator,
	"habr_career":         KindAggregator,
	"hh":                  KindAggregator,
	"himalayas":           KindAggregator,
	"infojobs":            KindAggregator,
	"instaffo":            KindAggregator,
	"jobdanmark":          KindAggregator,
	"jobicy":              KindAggregator,
	"jobnet":              KindAggregator,
	"jobspresso":          KindAggregator,
	"jobstash":            KindAggregator,
	"jobtech":             KindAggregator,
	"jobylon":             KindAggregator,
	"justjoin":            KindAggregator,
	"landingjobs":         KindAggregator,
	"mycareersfuture":     KindAggregator,
	"nodesk":              KindAggregator,
	"nofluffjobs":         KindAggregator,
	"powertofly":          KindAggregator,
	"reed":                KindAggregator,
	"remotedotcom":        KindAggregator,
	"remoteok":            KindAggregator,
	"remotive":            KindAggregator,
	"remotli":             KindAggregator,
	"schoolspring":        KindAggregator,
	"seek":                KindAggregator,
	"solidjobs":           KindAggregator,
	"startupandvc":        KindAggregator,
	"teamex":              KindAggregator,
	"tecla":               KindAggregator,
	"thehub":              KindAggregator,
	"themuse":             KindAggregator,
	"topco":               KindAggregator,
	"tyomarkkinatori":     KindAggregator,
	"usajobs":             KindAggregator,
	"vagas":               KindAggregator,
	"wantapply":           KindAggregator,
	"wantedkr":            KindAggregator,
	"weworkremotely":      KindAggregator,
	"whatjobs":            KindAggregator,
	"whatjobs-ae":         KindAggregator,
	"whatjobs-ar":         KindAggregator,
	"whatjobs-at":         KindAggregator,
	"whatjobs-au":         KindAggregator,
	"whatjobs-be":         KindAggregator,
	"whatjobs-bh":         KindAggregator,
	"whatjobs-br":         KindAggregator,
	"whatjobs-ca":         KindAggregator,
	"whatjobs-ch":         KindAggregator,
	"whatjobs-cl":         KindAggregator,
	"whatjobs-co":         KindAggregator,
	"whatjobs-de":         KindAggregator,
	"whatjobs-dk":         KindAggregator,
	"whatjobs-eg":         KindAggregator,
	"whatjobs-es":         KindAggregator,
	"whatjobs-fi":         KindAggregator,
	"whatjobs-fr":         KindAggregator,
	"whatjobs-gr":         KindAggregator,
	"whatjobs-hk":         KindAggregator,
	"whatjobs-hu":         KindAggregator,
	"whatjobs-id":         KindAggregator,
	"whatjobs-ie":         KindAggregator,
	"whatjobs-in":         KindAggregator,
	"whatjobs-it":         KindAggregator,
	"whatjobs-ke":         KindAggregator,
	"whatjobs-kw":         KindAggregator,
	"whatjobs-lu":         KindAggregator,
	"whatjobs-mx":         KindAggregator,
	"whatjobs-my":         KindAggregator,
	"whatjobs-nl":         KindAggregator,
	"whatjobs-no":         KindAggregator,
	"whatjobs-nz":         KindAggregator,
	"whatjobs-om":         KindAggregator,
	"whatjobs-pe":         KindAggregator,
	"whatjobs-ph":         KindAggregator,
	"whatjobs-pk":         KindAggregator,
	"whatjobs-pl":         KindAggregator,
	"whatjobs-pt":         KindAggregator,
	"whatjobs-py":         KindAggregator,
	"whatjobs-qa":         KindAggregator,
	"whatjobs-sa":         KindAggregator,
	"whatjobs-se":         KindAggregator,
	"whatjobs-sg":         KindAggregator,
	"whatjobs-sv":         KindAggregator,
	"whatjobs-th":         KindAggregator,
	"whatjobs-tr":         KindAggregator,
	"whatjobs-uk":         KindAggregator,
	"whatjobs-ve":         KindAggregator,
	"whatjobs-vn":         KindAggregator,
	"whatjobs-za":         KindAggregator,
	"workatastartup":      KindAggregator,
	"workingnomads":       KindAggregator,
	"2gis":                KindCareerSite,
	"alfabank":            KindCareerSite,
	"alignerr":            KindCareerSite,
	"amazon":              KindCareerSite,
	"apple":               KindCareerSite,
	"aviasales":           KindCareerSite,
	"avito":               KindCareerSite,
	"bairesdev":           KindCareerSite,
	"dataart":             KindCareerSite,
	"dodo":                KindCareerSite,
	"domclick":            KindCareerSite,
	"emagine":             KindCareerSite,
	"google":              KindCareerSite,
	"kuper":               KindCareerSite,
	"lamoda":              KindCareerSite,
	"lumenalta":           KindCareerSite,
	"meta":                KindCareerSite,
	"micro1":              KindCareerSite,
	"mts":                 KindCareerSite,
	"mtslink":             KindCareerSite,
	"onstrider":           KindCareerSite,
	"ozon":                KindCareerSite,
	"rwb":                 KindCareerSite,
	"sber":                KindCareerSite,
	"tbank":               KindCareerSite,
	"telegramcareers":     KindCareerSite,
	"uber":                KindCareerSite,
	"vk":                  KindCareerSite,
	"yandex":              KindCareerSite,
	"yandexcrowd":         KindCareerSite,
}

// kindOf looks up a provider's kind, defaulting to Unclassified.
func kindOf(provider string) string {
	if k, ok := providerKind[provider]; ok {
		return k
	}
	return KindUnclassified
}

// displayName turns a provider slug into a readable company name for the
// Aggregator kind's auto-filled company field, e.g. "remoteok" ->
// "Remoteok", "cryptocurrencyjobs" -> "Cryptocurrencyjobs". Deliberately
// simple — a curator can always fix the CSV row by hand afterward, and a
// slug-to-brand-name table for 238 providers is its own maintenance
// burden for a field nothing downstream depends on being exact.
func displayName(provider string) string {
	s := strings.ReplaceAll(provider, "-", " ")
	s = strings.ReplaceAll(s, "_", " ")
	words := strings.Fields(s)
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}
